spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/your-data-base'
    username: 'username'
    password: 'password'

#  jpa:
#    hibernate:
#      ddl-auto: create-drop # create, update
#    show-sql: true # enable jpa sql logs

server:
  port: '8080'


